# Generated by Django 4.2.5 on 2023-10-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("nombres", models.CharField(max_length=255)),
                ("apellidos", models.CharField(max_length=255)),
                ("dpi", models.CharField(max_length=13, unique=True)),
                ("genero", models.CharField(max_length=255)),
                ("escolaridad", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=75)),
                ("direccion", models.CharField(max_length=255)),
                ("etnia", models.CharField(max_length=255)),
                ("fecha_nacimiento", models.DateField()),
                ("edad", models.IntegerField()),
                ("password", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
